# From https://www.thethingsnetwork.org/docs/applications/python/index.html

'''import time
import ttn
from data_to_send import captureData

app_id = "iot-food-mgmt"
access_key = "NNSXS.3SKSOMT667KG4JY4IUALXJPJNNRPWEME3I7Q3FI.OWWDZHAP5PLF7NOW7AGIBPBBSMDDN3LE5L2J46PFJCPIDUOLYKMQ"

def uplink_callback(msg, client):
	print("Received uplink from ", msg.dev_id)
	print(msg)

def connect_callback(res, client):
	if res:
		print("Connection was successful.")
	else:
		print("Connection was unexpected.")

def downlink_callback(mid, client):
	print("Received downlink from ", mid)

def close_callback(res, client):
	if res:
		print("Disconnection was successful.")
	else:
		print("Disconnection was unexpected.")

MQTTClient(app_id, access_key, mqtt_address="", discovery_address="discovery.thethings.network:1900")
client.connect()
client.set_uplink_callback(uplink_callback)
client.set_connect_callback(connect_callback)
client.set_downlink_callback(downlink_callback)
client.set_close_callback(close_callback)
client.set_custom_payload_functions(encoder="", decoder="", validator="", converter="")
# read the file generated by transmitter code
sensor_data = captureData()
# send data
client.send(dev_id, sensor_data, port=1, conf=False, sched="replace")

client.close()'''


